### PR TITLE
Sprint 1

### PR DESCRIPTION
**Pull request by tmushayahama**
## Issues
https://github.com/geneontology/noctua-form/issues/162
https://github.com/geneontology/noctua-form/issues/185
https://github.com/geneontology/noctua-landing-page/issues/47
https://github.com/geneontology/noctua-form/issues/177

## Added

- Announcement Banner Sample

## Changed

- Fix Evidence getting lost after adding an input
- Added Uberon Life Stages on the happens during
- Activity Date now taking the last modified individua or evidence

## Testing

- Also add other Individuals like add has_ouput, part of etc to check if the evidence is not lost
- Edit the https://github.com/geneontology/noctua-announcements repo accordingly to see if the announcements change 

tagging @vanaukenk @ukemi

### CODE REVIEW

**Comment by vanaukenk** [comment]
#162 #185 #177 are tested and okay to move to production, but the announcements ticket needs more discussion and isn't ready to move to production.
@tmushayahama can you re-submit the PR without the announcements work/addition?

**Comment by tmushayahama** [comment]
@vanaukenk oh yes, it will not show up on production . This is only for dev.

**Comment by vanaukenk** [comment]
@tmushayahama 
But can we move the work for #162 #185 and #177 to production Noctua without also putting the announcements work into production?
I've tested and approved those three tickets for production, but don't want to put the announcements onto production yet.

**Comment by tmushayahama** [comment]
@vanaukenk yes, that what I meant on above. The production will not have the announcement components displaying. The code is for the dev server now, but not for production. I am about to PR to production

**Comment by vanaukenk** [comment]
See: https://github.com/geneontology/noctua-form/pull/202

**Comment by tmushayahama** [comment]
@vanaukenk that's PR to production without the announcements .

**Pull request merged**
