### PR TITLE
hard coded barista location issue 49 + extra

### PR DESCRIPTION
**Pull request by tmushayahama**
barista token fix by using

```ts
declare var global_barista_location: any;
const baristaLocation = typeof global_barista_location !== 'undefined' ? global_barista_location : 'http://barista-dev.berkeleybop.org';
```

- correct menu, adding BP and CC,
- Id on form entity labels
- Causal relationship correction
- Bio Phase vs Bio Process typo cause chaos

### CODE REVIEW

**Comment by kltm** [comment]
@vanaukenk I've put this onto `noctua-dev`. When you get a chance, could you take a look?

**Comment by vanaukenk** [comment]
@kltm 
I've tested login and subsequent moving around from landing page to form to graph.  
I stay logged in and the same barista_token is maintained across UIs.
Let me know if there's anything else specifically wrt the environmental variables issue you'd like me to check.
Otherwise, it looks okay to me.

**Comment by vanaukenk** [comment]
@tmushayahama will add correct link from Noctua form back to landing page

**Comment by kltm** [comment]
@vanaukenk As @tmushayahama said, the "final" noctua changes should already be on noctua-dev. Once this addition (https://github.com/geneontology/noctua-form/pull/51#issuecomment-576815333) is tested, we can work out the best time to switch.

**Comment by vanaukenk** [comment]
@tmushayahama @kltm 
I was testing again this morning and there is still the bug on noctua-dev that when I click on 'Noctua' at the top of the form, I go back to the landing page but lose my barista token and login.

image

**Pull request merged**
