### PR TITLE
Added the build https://github.com/geneontology/noctua-form-base/tree/bbca7e22fa0b4fe78fa5b1a48a45eee942f182e0

### PR DESCRIPTION
**Pull request by tmushayahama**
@kltm new noctua update

### CODE REVIEW

**Comment by kltm** [comment]
In the future, it would be good to name branches after the issues they are associated with, with one PR per issue.
Generally, a pattern I like, if the branch is in the repo with the tracker:
`issue-NNN-human-readable-label`
If the branch is in a different repo:
`issue-remote-repo-NNN-human-readable-label`
 For example my branch `issue-geneontology-minerva-212-add-validation-resp` here https://github.com/berkeleybop/bbop-graph-noctua/pull/3 refers to an issue in minerva.

**Comment by kltm** [comment]
And reference the issue in the PRs as well helps make it easier to track when should be known.

**Comment by kltm** [comment]
I think this looks good though. Is it good to get this one out now.

**Comment by tmushayahama** [comment]
Will try, it will kinda be difficult and time consuming @kltm to duplicate. The actual code repo is noctua-form-base https://github.com/geneontology/noctua-form-base that is where all the NF development is with all the correct issue branches. This repo mostly is for naming purposes, auto-generated, otherwise ART and NF and Search is technically one project.

**Comment by tmushayahama** [comment]
@kltm thanks

**Pull request merged**
