### PR TITLE
Sprint 3

### PR DESCRIPTION
**Pull request by tmushayahama**
### Issue
- https://github.com/geneontology/noctua-visual-pathway-editor/issues/43
### Added 
- comments view
- add multiple comments
- delete comments

tagging @vanaukenk @ukemi @pgaudet

### CODE REVIEW

**Comment by tmushayahama** [comment]
### Issue
- https://github.com/geneontology/noctua-visual-pathway-editor/issues/43
### Added 
- comments view
- add multiple comments
- delete comments

tagging @vanaukenk

**Comment by vanaukenk** [comment]
@tmushayahama 

I'm testing the new comments feature on the noctua-form and one difference I've noticed between prod and dev is that when I change a title on prod and click 'save', the title immediately updates in the bar at the top of the page.

On noctua-dev now, though, that no longer happens after clicking 'save'.  I had to refresh the page to see the new title.

Is this expected?

The automatic title update is preferred because it gives curators visual confirmation that the change they made has been made.  Otherwise, they will wonder if the change worked.

**Comment by vanaukenk** [comment]
I have the same question for the comments feature.

Once a curator adds a comment and clicks on 'save' can the number by the comments bubble be updated?

**Comment by vanaukenk** [comment]
Also, the new grouping of tools on the Noctua landing page looks fine to me and all the link work fine.

**Comment by tmushayahama** [comment]
@vanaukenk for me it is changing fine without refresh after pressing "save" button. even the comments number changes.

**Comment by vanaukenk** [comment]
Hmmm....I'm still seeing the same behavior I saw earlier on noctua-dev.  Let's screen share so you can see what I'm doing.

**Comment by vanaukenk** [comment]
Discussed with @tmushayahama 
Metadata will only update on models with individuals, so we decided to create a new ticket to add an error message pop-up that alerts curators not to edit metadata until they've created at least one annotation.

See: https://github.com/geneontology/noctua-form/issues/205

**Pull request merged**
